# Generated by Django 4.2.27 on 2026-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("SMS", "SMS"),
                    ("SOCIAL", "Social"),
                    ("VISHING", "Vishing/Voice"),
                ],
                default="EMAIL",
                max_length=10,
            ),
        ),
    ]
