# Generated by Django 4.2.27 on 2026-04-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermoduleprogress",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="usermoduleprogress",
            name="streak_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usermoduleprogress",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
